### ISSUE TITLE
Issues with Casper theme not being recognized

### ISSUE THREAD

**Issue by victorkernes** [now-examples/ghost#10]
I kept receiving this 500 error: `The currently active theme "casper" is missing.` Ended up cloning the actual **Ghost** repo here: https://github.com/TryGhost/Ghost

```
git clone https://github.com/TryGhost/Ghost.git
```
Then I continued running through the now-example directions and received this 500 error: `Failed to lookup view "index" in views directory "User/username/etc/etc/themes/casper"`

To solve this, I removed the casper theme directory and cloned the latest version of Casper: `https://github.com/TryGhost/Casper`

```
rm -R casper

// In the themes folder there should now be no more themes.
// Within the themes folder run the following:

git clone https://github.com/TryGhost/Casper.git

```

That should do the trick!

**Comment by toymachiner62** [comment]
This repo should be updated so that we don't have to manually copy the casper theme to our project though.

**Comment by TooTallNate** [comment]
This isn't happening for me using the latest example code. If you would like, try it the latest instructions in the Readme and let me know if you run into any issues.
