### ISSUE TITLE
Ghost 1.0

### ISSUE THREAD

**Issue by mds** [now-examples/ghost#3]
Hey Nate!

Would love to see this repo updated for Ghost 1.0 https://blog.ghost.org/1-0/ I used Zeit for a static site recently https://usecontrastcom recently and loved it. Itching to use it now for Ghost blogs.

—MDS

**Comment by TooTallNate** [comment]
Hey there, sorry for the late reply. The example is now up-to-date with Ghost v1. Give it a try and let me know if you have any issues!
